import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';

const Home: NextPage = () => {
  const { data, status } = useSession();

  if (status === 'loading') {
    return <div>'...Loading'</div>;
  } else if (status === 'unauthenticated') {
    return (
      <div>
        <button onClick={() => signIn()}>Sign In</button>
      </div>
    );
  }

  const name = data?.user?.name;

  return (
    <>
      <Head>
        <title>PESU Placement Information Tool</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{name}</h1>
        <button onClick={() => signOut()}>Sign Out</button>
      </div>
    </>
  );
};

export default Home;
